### ISSUE TITLE
Select spaces removed when mapping to property using mapto="property:..."

### ISSUE THREAD

**Issue by paulflakstad** [alkacon/opencms-core#54] opened 2012-05-18 11:32 UTC
When mapping text to property using mapto="property:...", some spaces are removed.

The removed spaces are those at the line-breaks in the control code. The problem appears only when viewing of the properties. A string fetched by reading an affected property value is fine, and will have no missing spaces.

Observed on OpenCms v8.0.4 (running on Tomcat / MySQL).

**Comment by aKandzior** [comment] 2016-01-08 14:26
Sorry for the rather late reply to this.

Can you please elaborate a bit further on the issue? Is this still relevant? 

If you, please provide a more complete example how to reproduce this.

**Comment by aKandzior** [comment] 2016-01-08 14:39
If no further activity happens here I will change this ticket in 3 months as "Won't fix".

**Comment by aKandzior** [comment] 2016-04-18 12:31
Closing this ticket because there has been no activity in the last 3 months.

**Closed by aKandzior** 2016-04-18 12:31 UTC
