### ISSUE TITLE
Validation error is not resetted after closing editor

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#478] opened 2017-02-08 10:11 UTC
To reproduce it in OpenCms 10.0.1 with /apollo-demo/element-pages/event/index.html:

1. Open event "Pre-Release Poster Party" (/apollo-demo/.content/events/ev_00003.xml)
2. Switch to German
3. Delete Content of field "Title"
4. Cancel editing
5. Re-open same resource
6. Edit "Title" in English

Saving is not possible now ("The content has validation errors within locale German (Germany)") even though German has no content at all.

Problem affects all content elements on the page now, until page is reloaded.

**Comment by tHerrmann** [comment] 2017-02-15 15:42
Could you please check, if this issue persists in the latest release? I could not reproduce it.

**Comment by kartobi** [comment] 2017-02-17 12:15
Ok. Need to do the upgrade first.
Is it possible just to adapt the version in gradle or do I need to wait for the upgrade wizard?

**Comment by kartobi** [comment] 2017-02-27 20:24
Problem still exist:
Step 3+4:
![step3 4](https://cloud.githubusercontent.com/assets/2276952/23378159/53bab478-fd2a-11e6-8e3b-914e0e5a9c18.png)
Step 6:
![step6](https://cloud.githubusercontent.com/assets/2276952/23378160/53cdc720-fd2a-11e6-8662-b27e66d50468.png)

Wherever a validation error occurs, and the editor ist closed by (x) without solving the error, this error "remains". Even when editing a different content element (e.g. "Annual Autumn Assembly")

**Comment by patric-dosch-vi** [comment] 2017-03-08 11:09
hey @tHerrmann, this error here is slowly becoming a problem. Have you understand the steps? 

> Wherever a validation error occurs and the editor ist closed by (x) without solving the error, this error "remains". Even when editing a different content element 
I think he is easy to reproduce and it is still in 10.5.1

Best, Patric

**Comment by tHerrmann** [comment] 2017-03-24 13:52
I think I have fixed the issue, please check 13690ea247639404e755a2e26196d38c34b79c90 if the fix works for you as well.

**Comment by patric-dosch-vi** [comment] 2017-04-03 09:01
hello @tHerrmann, many thanks for the fix. I'm not very familiar with GWT, how can we most easily integrate this fix into our system?

**Comment by tHerrmann** [comment] 2017-04-03 19:28
Hi @patric-dosch-vi,
you can either check out the current head of branch_10_5_x and use Gradle to build the tasks jar, jar_org.opencms.gwt and widgetSetJar to replace the JARs in the OpenCms 10.5.1 release. Or you could check out the tag build_10_5_1 and cherry pick the fix, run the tasks jar and jar_org.opencms.gwt to replace the release versions.

**Comment by patric-dosch-vi** [comment] 2017-04-06 15:00
hey @tHerrmann, many thanks. I thought something similar :)

**Comment by aKandzior** [comment] 2017-04-07 15:14
Tried to reproduce the issue on latest nightly build without success. Fix seems to be working.

**Comment by tHerrmann** [comment] 2017-07-12 10:01
The fix to this issue has been released with version [10.5.2](https://github.com/alkacon/opencms-core/releases/tag/build_10_5_2).

**Closed** 2017-07-12 10:01 UTC
Labels: Already fixed
