### ISSUE TITLE
OpenCMS 8.5.2 - Installation error

### ISSUE THREAD

**Issue by mistnick** [alkacon/opencms-core#243] opened 2014-05-03 22:20 UTC
Hi all,

I am trying to install OpenCMS on a Windows 2012 server. My configuration is the following:

- Tomcat 6
- Oracle JDK 1.6
- Apache2 with mod_proxy
- MySQL

During the setup, after the step_8, I get this error:

Shutdown completed, total uptime was 00:08:55.
Shutting down OpenCms, version 8.5.0 in web application "opencms850"

	at org.opencms.setup.CmsSetupWorkplaceImportThread.run(CmsSetupWorkplaceImportThread.java:202)
	at org.opencms.setup.CmsSetupWorkplaceImportThread.kill(CmsSetupWorkplaceImportThread.java:110)
	at org.opencms.main.CmsShell.exit(CmsShell.java:571)
java.lang.NullPointerException
	at org.opencms.setup.CmsSetupWorkplaceImportThread.run(CmsSetupWorkplaceImportThread.java:187)
	at org.opencms.main.CmsShell.start(CmsShell.java:663)
	at org.opencms.main.CmsShell.executeCommands(CmsShell.java:835)
	at org.opencms.main.CmsShell.executeCommand(CmsShell.java:760)
${user}@${project}>java.lang.NullPointerException
${user}@${project}># Turn echo on
	at org.opencms.setup.CmsSetupWorkplaceImportThread.run(CmsSetupWorkplaceImportThread.java:148)
	at org.opencms.main.CmsShell.<init>(CmsShell.java:447)
	at org.opencms.main.OpenCmsCore.upgradeRunlevel(OpenCmsCore.java:1872)
	at org.opencms.main.OpenCmsCore.initConfiguration(OpenCmsCore.java:1256)
	at org.opencms.search.CmsSearchManager.initialize(CmsSearchManager.java:1398)
	at org.opencms.search.CmsSearchManager.initializeIndexes(CmsSearchManager.java:1419)
	at org.opencms.search.CmsSearchManager.initSearchIndexes(CmsSearchManager.java:2221)
	at org.opencms.search.solr.CmsSolrIndex.initialize(CmsSolrIndex.java:304)
	at org.opencms.search.CmsSearchManager.registerSolrIndex(CmsSearchManager.java:1610)
java.lang.NullPointerException
	
OpenCms property file: "D:\java\server\Tomcat6.0\opencms850\WEB-INF\config\opencms.properties".
OpenCms WEB-INF path:  "D:\java\server\Tomcat6.0\opencms850\WEB-INF\". 

I don't understand what is the problem. Do you have any idea?

Thanks and regards

**Comment by aKandzior** [comment] 2016-01-08 13:25
Outdated and clearly not a bug but a support issue. Closing this ticket.

**Closed by aKandzior** 2016-01-08 13:25 UTC
