### ISSUE TITLE
broken url on scaled image when re-saving page in sub-site

### ISSUE THREAD

**Issue by budq** [alkacon/opencms-core#78] opened 2012-09-07 21:18 UTC
I am getting an error on links to static exports of scaled images within a sub-site domain.  Unscaled images work fine, but scaled images break upon a re-save of an html page.  They work when they are first added, but if I re-edit the page while within the sub-site (not the Site: /) any previously added scaled image breaks. I have tried this on multiple sites and get a consistent result.  Here is a step-by-step of my setup and where it works and what breaks it.  (Sorry for the long post)

fresh install in ROOT.war
https://192.168.10.20/

I changed the following in the config files:

WEB-INF/config/opencms-system.xml:

    <sites>
      <workplace-server>https://192.168.10.20</workplace-server>
      <default-uri>/</default-uri>
      <shared-folder>/shared/</shared-folder>
      <site server="http://192.168.10.20" uri="/sites/default/"/>
      <site server="http://192.168.10.14" uri="/sites/test/"/>
    </sites>

changed:

      <param name="compatibility.support.webAppNames">/opencms/opencms/</param>

to:

      <param name="compatibility.support.webAppNames">/</param>

WEB-INF/config/opencms-importexport.xml:
changed:

                <staticexporthandler>org.opencms.staticexport.CmsOnDemandStaticExportHandler</staticexporthandler>

to:

                <staticexporthandler>org.opencms.staticexport.CmsAfterPublishStaticExportHandler</staticexporthandler>

changed:

                        <userelativelinks>false</userelativelinks>

to:

                        <userelativelinks>true</userelativelinks>

added html to export:

                <defaultsuffixes>
                        <suffix key=".html"/>
                        <suffix key=".jpg"/>
                        <suffix key=".gif"/>

add site:
/sites/test
and make the URL http://192.168.10.14

/etc/tomcat/server.xml:
   <Connector port="8081" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443"
               emptySessionPath="true"
               proxyName="192.168.10.14" proxyPort="80" />

/etc/init.d/tomcat restart

created an image gallery
/sites/test/images

uploaded images to it and published.

Site: /
Location: /sites/test/

New Page with free text - index.html
Edit index.html
In WYSIWYG - Image gallery - /sites/test/images/

View HTML (in WYSIWYG):
src="/opencms/sites/test/images/IMG_1777.JPG"

save and publish

export/sites/test/index.html looks right for the export:
src="images/IMG_1777.JPG"

http://192.168.10.14/index.html looks correct.

--------------------------
edit index.html again at:
Site: /
Location: /sites/test/

View HTML (in WYSIWYG):
src="http://192.168.10.14/opencms/images/IMG_1777.JPG"
(the url of the sub site is correct)
save and publish

export/sites/test/index.html looks right for the export:
src="images/IMG_1777.JPG"

http://192.168.10.14/index.html looks correct.

--------------------------
edit index.html again at:
Site: /sites/test/
Location: /

View HTML (in WYSIWYG):
src="https://192.168.10.20/opencms/images/IMG_1777.JPG"
(now it is giving me the url of the cms server, not the subsite)
save and publish

export/sites/test/index.html looks right for the export:
src="images/IMG_1777.JPG"

http://192.168.10.14/index.html looks correct.

-----------------------
Now try with scaling:

edit index.html again at:
Site: /
Location: /sites/test/

Edit index.hmtl
In WYSIWYG - Image gallery - /sites/test/images/
Scale
Select

View HTML (in WYSIWYG):
src="/opencms/sites/test/images/IMG_1777.JPG?__scale=h:149,w:200"
save and publish

export/sites/test/index.html looks right for the export:
src="images/IMG_1777.JPG_1795545173.jpg"
correct with relative link and a newly created scaled image.

http://192.168.10.14/index.html looks correct.

-----------------------
edit index.html again at:
Site: /
Location: /sites/test/

View HTML (in WYSIWYG):
src="http://192.168.10.14/opencms/images/IMG_1777.JPG?__scale=h:149,w:200"
has the correct url for the subsite
save and publish

export/sites/test/index.html looks right for the export:
src="images/IMG_1777.JPG_1795545173.jpg"
correct with relative link and a newly created scaled image.

http://192.168.10.14/index.html looks correct.

-----------------------
edit index.html again inside the subsite:
Site: /sites/test/
Location: /

View HTML (in WYSIWYG):
src="https://192.168.10.20/opencms/images/IMG_1777.JPG?__scale=h:149,w:200"
(now it is giving me the url of the cms server, not the subsite)
save and publish

export/sites/test/index.html now has static link to wrong host:
src="https://192.168.10.20/opencms/images/IMG_1777.JPG?__scale=h:149,w:200"

http://192.168.10.14/index.html has a broken image if I am not logged into the cms instance.

-------------------------
Now to try with scaling added inside the sub site:

Site: /sites/test
Location: /

Edit index.hmtl
In WYSIWYG - Image gallery - /sites/test/images/
Scale
Select

View HTML (in WYSIWYG):
 src="/opencms/images/IMG_1777.JPG?__scale=h:74,w:100" alt="IMG_1777"

export/sites/test/index.html looks right for the export:
src="images/IMG_1777.JPG"

http://192.168.10.14/index.html looks correct.

--------------------------
edit index.html again at:
Site: /sites/test/
Location: /

View HTML (in WYSIWYG):
src="https://192.168.10.20/opencms/images/IMG_1777.JPG?__scale=h:74,w:100"
(now it is giving me the url of the cms server, not the subsite)
save and publish

export/sites/test/index.html now has static link to wrong host:
src="https://192.168.10.20/opencms/images/IMG_1777.JPG?__scale=h:74,w:100" 

http://192.168.10.14/index.html has a broken image if I am not logged into the cms instance.

**Comment by aKandzior** [comment] 2016-01-08 14:20
Can you please check if this is still an issue in 9.5?

**Comment by aKandzior** [comment] 2016-04-18 12:38
Please check if this is still an issue with either OpenCms 9.5.1 or 10.0.0. If I do not hear back from you within 3 months I will assume the issue is no longer relevant and close it.

**Comment by aKandzior** [comment] 2016-10-01 03:26
No feedback. Closing this issue.

**Closed by aKandzior** 2016-10-01 03:26 UTC
