### ISSUE TITLE
NullpointerException at CmsLog

### ISSUE THREAD

**Issue by tpinky** [alkacon/opencms-core#288] opened 2014-11-05 12:46 UTC
During the the initialization of the CmsShell an exception is thrown, cause the CmsLog.INIT is maybe null.
CmsShell shell = new CmsShell(webInf, (servletMapping.isEmpty() ? null : servletMapping), null, "${user}@${project}>", additionalShellCommands);

java.lang.ExceptionInInitializerError
	at org.opencms.main.OpenCmsCore.initMembers(OpenCmsCore.java:1471)
	at org.opencms.main.OpenCmsCore.<init>(OpenCmsCore.java:313)
	at org.opencms.main.OpenCmsCore.getInstance(OpenCmsCore.java:333)
	at org.opencms.main.CmsShell.<init>(CmsShell.java:490)
	at org.opencms.main.CmsShell.<init>(CmsShell.java:448)
	at main.CmsShellMain.main(CmsShellMain.java:91)
Caused by: java.lang.NullPointerException
	at org.opencms.i18n.CmsLocaleManager.setDefaultLocale(CmsLocaleManager.java:367)
	at org.opencms.i18n.CmsLocaleManager.<clinit>(CmsLocaleManager.java:141)
	... 6 more

**Comment by marcjohnen** [comment] 2015-05-13 10:54
Hi tpinky,
can you tell me why you closed this? I'm having this problem when starting the shell via the ant-opencms-scripts (http://johnen.biz/en/blog/OpenCms-Module-Manager/) in OpenCms 9.5.1.
Adding CmsLog.INIT = LogFactory.getLog("org.opencms.init"); to the CmsShell-class helps.
Did you find another solution?
Thanks
Marc

**Comment by tpinky** [comment] 2015-05-19 13:57
Hi Marc,

i didn't investigated the bug further. So unfortunately I have no other 
solution.

Greetings
Thomas

Am 13.05.2015 um 12:54 schrieb marcjohnen:
>
> Hi tpinky,
> can you tell me why you closed this? I'm having this problem when 
> starting the shell via the ant-opencms-scripts 
> (http://johnen.biz/en/blog/OpenCms-Module-Manager/) in OpenCms 9.5.1.
> Adding CmsLog.INIT = LogFactory.getLog("org.opencms.init"); to the 
> CmsShell-class helps.
> Did you find another solution?
> Thanks
> Marc
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alkacon/opencms-core/issues/288#issuecomment-101625117>.
>


-- 
componio GmbH
Robert-Bosch-Straße 7
D - 64293  Darmstadt
Tel:	+49.6151.500.367.16
Office:	+49.6151.500.367.0
Fax:	+49.6151.500.367.6
Internet: http://www.componio.net
Twitter: http://www.twitter.com/componio
E-Mail:	componio@componio.net
Geschäftsführer: Fabian Huschka
HRB 9624 - Registergericht Amtsgericht Darmstadt

**Comment by marcjohnen** [comment] 2015-05-19 14:01
Hi Thomas,
ok, thank you. So I'd say this bug still exists and shouldn't be closed.
Greetings
Marc

**Comment by tpinky** [comment] 2015-05-19 14:04
Hi Marc,

I have closed this issue, because this small woraround worked for me.
We use the workaround it in an own class for our Netbeans Plugin for 
OpenCms.
It was no big deal for us.

The problem is, that the CmsLog.INIT variable isn't initialized properly 
during the start of the CmsShell.

Greeting
Thomas


Am 19.05.2015 um 15:56 schrieb Thomas Pinkowski:
> Hi Marc,
>
> i didn't investigated the bug further. So unfortunately I have no 
> other solution.
>
> Greetings
> Thomas
>
> Am 13.05.2015 um 12:54 schrieb marcjohnen:
>>
>> Hi tpinky,
>> can you tell me why you closed this? I'm having this problem when 
>> starting the shell via the ant-opencms-scripts 
>> (http://johnen.biz/en/blog/OpenCms-Module-Manager/) in OpenCms 9.5.1.
>> Adding CmsLog.INIT = LogFactory.getLog("org.opencms.init"); to the 
>> CmsShell-class helps.
>> Did you find another solution?
>> Thanks
>> Marc
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/alkacon/opencms-core/issues/288#issuecomment-101625117>.
>>
>
>
> -- 
> componio GmbH
> Robert-Bosch-Straße 7
> D - 64293  Darmstadt
> Tel:	+49.6151.500.367.16
> Office:	+49.6151.500.367.0
> Fax:	+49.6151.500.367.6
> Internet:http://www.componio.net
> Twitter:http://www.twitter.com/componio
> E-Mail:	componio@componio.net
> Geschäftsführer: Fabian Huschka
> HRB 9624 - Registergericht Amtsgericht Darmstadt


-- 
componio GmbH
Robert-Bosch-Straße 7
D - 64293  Darmstadt
Tel:	+49.6151.500.367.16
Office:	+49.6151.500.367.0
Fax:	+49.6151.500.367.6
Internet: http://www.componio.net
Twitter: http://www.twitter.com/componio
E-Mail:	componio@componio.net
Geschäftsführer: Fabian Huschka
HRB 9624 - Registergericht Amtsgericht Darmstadt

**Comment by marcjohnen** [comment] 2015-05-19 14:12
Hi Thomas,
still I consider this a bug as it can be reproduced and it would be nice to fix it so we don't have to patch.
Thanks for posting the solution btw. it saved me some time.
Greetings
Marc

**Comment by tpinky** [comment] 2015-05-19 18:40
Look at the discussion above. 
I'm reopening the issue.

**Comment by gWestenberger** [comment] 2016-01-08 16:33
Actually, this should work from 9.5.0 onwards as long as your WEB-INF/classes folder is part of the classpath.

**Comment by aKandzior** [comment] 2016-04-18 12:36
Closing this ticket because there has been no activity in the last 3 months and the issue is solved with OpenCms 9.5.x

**Closed by aKandzior** 2016-04-18 12:36 UTC
