### ISSUE TITLE
Error Importing Module - OpenCMS

### ISSUE THREAD

**Issue by evanorue** [alkacon/opencms-core#250] opened 2014-05-27 20:34 UTC
When I try to import a module I've this error, at least I can fix it removing the duplicate value from opencms-module.xml but when I try it again it seems that the importing module tool insert again the duplicate value and again I receive this error:

Importing module ...  ... Exception org.opencms.configuration.CmsConfigurationException: Resource type "importad" (id: 2,040) from module "com.tfsla.diario.admin" conflicts with already configured resource type "importad" (id: 2,040).
You must use different names and ids for all resource types.
at org.opencms.loader.CmsResourceManager.initResourceTypes(CmsResourceManager.java:1332)
at org.opencms.loader.CmsResourceManager.initialize(CmsResourceManager.java:1022)
at org.opencms.module.CmsModuleImportExportHandler.importModule(CmsModuleImportExportHandler.java:579)
at org.opencms.module.CmsModuleImportExportHandler.importData(CmsModuleImportExportHandler.java:381)
at org.opencms.importexport.CmsImportExportManager.importData(CmsImportExportManager.java:682)
at org.opencms.workplace.threads.CmsDatabaseImportThread.run(CmsDatabaseImportThread.java:96)

**Comment by aKandzior** [comment] 2016-01-08 13:17
This is not a bug but a support issue. You are importing the same resource type multiple times. You must fist delete the existing resource type. 

Closing this issue.

**Closed by aKandzior** 2016-01-08 13:17 UTC
