### ISSUE TITLE
Performance issue (slowness in page loading) while user try to login into opencms

### ISSUE THREAD

**Issue by Sanjaylandge** [alkacon/opencms-core#273] opened 2014-08-01 10:57 UTC
Hi Opencms Dev. Team,
       I am using opencms(8.0.2) in my project, where I have use "loginUser(String,String)" method of CmsJspActionElement class for login into opencms, however that process taking too long time to execute (near 1 minute to login a user). Due to that lagging time my application taking long time to load.
    As per my analysis, implementation of loginUser() method state that first process login for user then read online project for that user then switch the user and set context for user.      
I am not confirm that out of all above mentioned states of loginUser() method taking too long time which causes delay to load my application page.

Please let me know is their any solution for the same ASAP or does it works faster with your next versions like as 9.0.1.

Thanks in Advance.
Regards,
Sanjay.

**Comment by aKandzior** [comment] 2016-01-08 12:29
Not able to reproduce this issue, closing.

**Closed by aKandzior** 2016-01-08 12:29 UTC
