### ISSUE TITLE
Warp time doesn't work. 

### ISSUE THREAD

**Issue by Areks** [alkacon/opencms-core#199] opened 2013-12-02 06:12 UTC
When i create some resources with date release in future and want to view it using warp time settings, i get just empty page. I analized code and find that the problem is in reading resources for container. 
When we evoke CmsJspTagContainer methods
```Java
	OpenCmsCore.initCmsObject(CmsObject) line: 853	
	OpenCms.initCmsObject(CmsObject) line: 596	
	CmsElementUtil.<init>(CmsObject, String, HttpServletRequest, HttpServletResponse, Locale) line: 151	
	CmsContainerpageService.getSerializedElementInfo(CmsObject, HttpServletRequest, HttpServletResponse, CmsContainerElementBean) line: 199	
	CmsJspTagContainer.getElementInfo(CmsObject, CmsContainerElementBean) line: 654	
	CmsJspTagContainer.printElementWrapperTagStart(boolean, CmsObject, CmsContainerElementBean, boolean) line: 581	
	CmsJspTagContainer.renderContainerElement(HttpServletRequest, CmsObject, CmsJspStandardContextBean, CmsContainerElementBean, Locale, boolean) line: 861	
	CmsJspTagContainer.doStartTag() line: 347
```
i saw the next code inside CmsElementUtil  constructor 
```Java
m_cms = OpenCms.initCmsObject(cms); (i think you try to copy CmsObject)
```
But, the method initCmsObject change request time to current time, so any "time wrap" setting will overwrite here.

**Comment by aKandzior** [comment] 2016-04-18 12:39
Please check if this is still an issue with either OpenCms 9.5.1 or 10.0.0. If I do not hear back from you within 3 months I will assume the issue is no longer relevant and close it.

**Comment by aKandzior** [comment] 2016-10-01 03:25
No feedback. Closing this issue.

**Closed by aKandzior** 2016-10-01 03:25 UTC
