### ISSUE TITLE
Inheritance Group: Edit point of the removed elements doesn't show

### ISSUE THREAD

**Issue by rgaviras** [alkacon/opencms-core#336] opened 2015-08-21 10:14 UTC
When you hide an element in an Inheritance group the Edit point (Bulleye) it doesn't appear so it is not possible to manage the element options.

It seems to be a js bug.

A workaround is adding this css rule on your template css:

.org-opencms-gwt-client-ui-css-I_CmsToolbarButtonLayoutBundle-I_CmsToolbarButtonCss-toolbarSelection .org-opencms-gwt-client-ui-css-I_CmsDirectEditCss-optionBar .org-opencms-gwt-client-ui-css-I_CmsToolbarButtonLayoutBundle-I_CmsToolbarButtonCss-toolbarSelection, .org-opencms-gwt-client-ui-css-I_CmsToolbarButtonLayoutBundle-I_CmsToolbarButtonCss-toolbarSelection .org-opencms-gwt-client-ui-css-I_CmsDirectEditCss-optionBar.org-opencms-gwt-client-ui-css-I_CmsLayoutBundle-I_CmsStateCss-cmsHovering .cmsState {
  display: inline-block !important;
}

**Comment by tHerrmann** [comment] 2015-10-01 13:38
This behaviour is intended. You can only edit elements that are visible on the current page.
In case there was no other way to edit the element settings, you could still set the element visible, edit it and hide it again. 
Is that something that is really bothering you?

**Comment by aKandzior** [comment] 2016-01-04 12:41
Closing this issue since the function is working as designed and no further feedback was given to what we should improve.

**Closed by aKandzior** 2016-01-04 12:41 UTC
