### ISSUE TITLE
change 9.5.2 template model will  change all page created by it 

### ISSUE THREAD

**Issue by lztang1964** [alkacon/opencms-core#335] opened 2015-08-20 08:43 UTC
OpenCms document says if the temlate model hasn't element group,the page created and temlate model will indepent,but in 9.5.2 ,if change template model,the page created by it will also be changed even if the temlate model hasn't any element group.

I remenber 9.5.1 hasn't this problem!

**Comment by tHerrmann** [comment] 2015-10-01 13:29
Could you describe in more detail, what you do, what is happening and what the expected behaviour would be? If possible, use the demo contents as an example. That way we can reproduce the issue more easily.

**Comment by aKandzior** [comment] 2016-01-04 12:40
Closing this because we are unable to reproduce the issue and no further feedback was provided.

**Closed by aKandzior** 2016-01-04 12:40 UTC
