### ISSUE TITLE
static export issue in OpenCms 9.0.1

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#260] opened 2014-06-14 16:18 UTC
Used org.opencms.staticexport.CmsOnDemandStaticExportHandler
Lists of resources cannot be automatic re-export after modify the content of the reources.

**Comment by aKandzior** [comment] 2016-01-08 13:04
Sorry but we are not able to reproduce your issue with this description. Closing this ticket.

**Closed by aKandzior** 2016-01-08 13:04 UTC
