### ISSUE TITLE
List content page not loaded

### ISSUE THREAD

**Issue by Shaand** [alkacon/opencms-core#266] opened 2014-07-01 17:31 UTC
In Opencms workplace, when the XSD list content load with more than 100 records are displayed with the below error

Error:
A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.
Script: https://hostname/resources/ade/contenteditor/4B1E132EC7B3A62F862AB372B70B96A8.cache.html:5002

The browser stop completely to load the page at this point.

Please advise us how to solve this issue

**Comment by aKandzior** [comment] 2016-01-08 12:51
This is apparently because of some sort of custom script running in the browser. 

Closing this because it's a support case and not a bug.

**Closed by aKandzior** 2016-01-08 12:51 UTC
