### ISSUE TITLE
[Opencms 10 to 13] - Error triying to run the upgrade wizard

### ISSUE THREAD

**Issue by rgaviras** [alkacon/opencms-core#741] opened 2022-07-06 16:51 UTC
After introduce the user and password, when press continue,  we got a null pointer exception... we are stucked! don't know what to check
This is the log:

(Check the message at the button)

![captura (002)](https://user-images.githubusercontent.com/1841474/177602868-a3815c8e-c302-49b9-8d29-d571fa53940c.png)

--- opencms.log ---

06 jul 2022 18:44:18,203 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:3328] . Runlevel change      : Switching from 1 to 2
06 jul 2022 18:44:18,203 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1393] .
06 jul 2022 18:44:18,204 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1394] .
06 jul 2022 18:44:18,204 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1395] .
06 jul 2022 18:44:18,204 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1396] . This is OpenCms 13.0.
06 jul 2022 18:44:18,204 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1402] .
06 jul 2022 18:44:18,204 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1402] . Copyright (c) 2002 - 2022 Alkacon Software GmbH & Co. KG
06 jul 2022 18:44:18,204 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1402] . OpenCms comes with ABSOLUTELY NO WARRANTY
06 jul 2022 18:44:18,205 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1402] . This is free software, and you are welcome to
06 jul 2022 18:44:18,205 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1402] . redistribute it under certain conditions.
06 jul 2022 18:44:18,205 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1402] . Please see the GNU Lesser General Public Licence for
06 jul 2022 18:44:18,205 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1402] . further details.
06 jul 2022 18:44:18,205 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1402] .
06 jul 2022 18:44:18,205 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1404] .                      ...............................................................
06 jul 2022 18:44:18,206 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1405] . Startup time         : Jul 6, 2022 6:44:18 PM
06 jul 2022 18:44:18,206 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1407] . OpenCms version      : 13.0 [Release #26 (build_13_0_0 - b29a7d8) 2022-04-12 12:31]
06 jul 2022 18:44:18,207 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1414] . OpenCms webapp name  : tc
06 jul 2022 18:44:18,207 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1416] . OpenCms servlet path : /opencms
06 jul 2022 18:44:18,207 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1418] . OpenCms context      : /tc/opencms
06 jul 2022 18:44:18,207 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1420] . OpenCms WEB-INF path : /opt/apache-tomcat-8.5.23/webapps/tc/WEB-INF/
06 jul 2022 18:44:18,207 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1422] . OpenCms property file: /opt/apache-tomcat-8.5.23/webapps/tc/WEB-INF/config/opencms.properties
06 jul 2022 18:44:18,207 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1428] . OpenCms log file     : /opt/apache-tomcat-8.5.23/webapps/tc/WEB-INF/logs/opencms.log
06 jul 2022 18:44:18,773 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1447] . System file.encoding : UTF-8
06 jul 2022 18:44:18,789 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1453] . Ethernet address used: 00:50:56:A6:7C:30
06 jul 2022 18:44:18,790 [r:U8qswE]  INFO [org.opencms.main.CmsSystemInfo: 859] . Server name is       : OpenCmsServer
06 jul 2022 18:44:18,790 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1468] . Java VM in use       : Java HotSpot(TM) 64-Bit Server VM 25.131-b11 mixed mode Oracle Corporation
06 jul 2022 18:44:18,790 [r:U8qswE]  INFO [  org.opencms.main.OpenCmsCore:1472] . Operating sytem      : Linux 3.10.0-693.21.1.el7.x86_64 amd64
06 jul 2022 18:44:18,862 [r:U8qswE] ERROR [din.server.DefaultErrorHandler:  58]  {request_id=U8qswE, request_url=http://172.21.49.18:8080/tc/update/UIDL/?v-uiId=0}
java.lang.NullPointerException: null
        at org.opencms.main.CmsShell.validateUser(CmsShell.java:1176) ~[opencms.jar:13.0]
        at org.opencms.setup.CmsUpdateBean.isValidUser(CmsUpdateBean.java:697) ~[opencms-setup.jar:?]
        at org.opencms.setup.updater.dialogs.CmsUpdateStep04SettingsDialog$UserValidator.validate(CmsUpdateStep04SettingsDialog.java:56) ~[opencms-setup.jar:?]
        at com.vaadin.v7.ui.AbstractField.validate(AbstractField.java:967) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
        at com.vaadin.v7.ui.AbstractField.validate(AbstractField.java:932) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
        at com.vaadin.v7.ui.AbstractField.isValid(AbstractField.java:905) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
        at org.opencms.setup.updater.dialogs.CmsUpdateStep04SettingsDialog.submitDialog(CmsUpdateStep04SettingsDialog.java:141) ~[opencms-setup.jar:?]
        at org.opencms.setup.updater.dialogs.A_CmsUpdateDialog$2.buttonClick(A_CmsUpdateDialog.java:140) ~[opencms-setup.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:706) ~[vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399) ~[vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363) ~[vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1190) ~[vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.ui.Button.fireClick(Button.java:384) ~[vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.14.3.jar:8.14.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155) ~[vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116) ~[vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:442) [vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:407) [vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:275) [vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91) [vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1637) [vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464) [vaadin-server-8.14.3.jar:8.14.3]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.33]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.33]
        at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:150) [opencms.jar:13.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.33]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.1.jar:2.17.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.33]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.33]
        at psiprobe.Tomcat85AgentValve.invoke(Tomcat85AgentValve.java:38) [psi-probe-tomcat85-3.5.3.jar:3.5.3]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.33]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) [catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.33]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.33]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-coyote.jar:8.5.33]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.33]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-coyote.jar:8.5.33]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.33]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.33]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.33]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
06 jul 2022 18:44:18,886 [r:U8qswE] ERROR [din.server.DefaultErrorHandler:  58]  {request_id=U8qswE, request_url=http://172.21.49.18:8080/tc/update/UIDL/?v-uiId=0}
java.lang.NullPointerException: null
        at org.opencms.main.CmsShell.validateUser(CmsShell.java:1176) ~[opencms.jar:13.0]
        at org.opencms.setup.CmsUpdateBean.isValidUser(CmsUpdateBean.java:697) ~[opencms-setup.jar:?]
        at org.opencms.setup.updater.dialogs.CmsUpdateStep04SettingsDialog$UserValidator.validate(CmsUpdateStep04SettingsDialog.java:56) ~[opencms-setup.jar:?]
        at com.vaadin.v7.ui.AbstractField.validate(AbstractField.java:967) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
        at com.vaadin.v7.ui.AbstractField.validate(AbstractField.java:932) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
        at com.vaadin.v7.ui.AbstractField.getErrorMessage(AbstractField.java:1041) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
        at com.vaadin.ui.AbstractComponent.beforeClientResponse(AbstractComponent.java:696) ~[vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.v7.ui.AbstractLegacyComponent.beforeClientResponse(AbstractLegacyComponent.java:165) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
        at com.vaadin.v7.ui.AbstractField.beforeClientResponse(AbstractField.java:1684) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
        at com.vaadin.v7.ui.AbstractTextField.beforeClientResponse(AbstractTextField.java:113) ~[vaadin-compatibility-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:126) [vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:125) [vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) [vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1637) [vaadin-server-8.14.3.jar:8.14.3]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464) [vaadin-server-8.14.3.jar:8.14.3]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.33]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.33]
        at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:150) [opencms.jar:13.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.33]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.1.jar:2.17.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.33]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.33]
        at psiprobe.Tomcat85AgentValve.invoke(Tomcat85AgentValve.java:38) [psi-probe-tomcat85-3.5.3.jar:3.5.3]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.33]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) [catalina.jar:8.5.33]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.33]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.33]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-coyote.jar:8.5.33]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.33]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-coyote.jar:8.5.33]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.33]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.33]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.33]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

-------------------------------------------------------------------------

**Comment by gWestenberger** [comment] 2022-09-29 09:54
This turned out to be caused by conflicts between library JARs from OpenCms 13 and additional JARs which were added to the old installation. Closing.

**Closed by gWestenberger** 2022-09-29 09:54 UTC
