### ISSUE TITLE
Rewritten URL while saving a page.

### ISSUE THREAD

**Issue by TL-IT** [alkacon/opencms-core#79] opened 2012-09-13 21:24 UTC
When saving a just created page with a link/url on it, it's rewritten after save. The url is then not the correct url anymore. Example:
href="http://www.r-vent.be/site/"
Will become after save:
href="http://www.rvent.be/site/"

The '-' sign in the url part "www.r-vent.be" has dissapeared..

**Comment by aKandzior** [comment] 2016-01-08 14:17
Unable to reproduce with the data provided, possibly a setup problem.

Closing this ticket as WORKSFORME.

**Closed** 2016-01-08 14:19 UTC
Labels: Works for me
