### ISSUE TITLE
Passwords during setup in clear text (branch_9_0_x)

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#280] opened 2014-09-30 08:07 UTC
The current setup GUI requests the credentials of two database users. The corresponding password fields are in clear text and should be shadowed.(See attachment)

![alkacon_opencms_setup_wizard_-_2014-09-30_10 03 14](https://cloud.githubusercontent.com/assets/790448/4454983/da70ffe0-4878-11e4-8ec2-f7ff505f3260.png)

**Comment by aKandzior** [comment] 2016-01-08 11:26
This is not a bug but an improvement. 

FIX: If you install OpenCms to an environment where security matters, just ask the people that are in the same room with you to look away when you enter the password.

Closing since a fix is available ;)

**Closed by aKandzior** 2016-01-08 11:26 UTC

**Comment by gallardo** [comment] 2016-10-08 05:55
Unfortunately, the views in our offices are not so convincing ;-) It'd be by the way big fun in a big conference presentation!

I'd rather had this fixed with https://github.com/alkacon/opencms-core/pull/429
