### ISSUE TITLE
OpenCms 12 exception after installed

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#729] opened 2021-10-13 10:02 UTC
Install and restart Tomcat 

View：			
/opencms/mercury-demo/home/	

HTTP 500		
				
Log:
```			
13-Oct-2021 17:51:11.854 SEVERE [http-nio-8000-exec-3] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.ser
vice() for servlet [jsp] threw exception
        org.apache.jasper.JasperException: The absolute uri: [http://java.sun.com/jsp/jstl/core] cannot be resolved in e
ither web.xml or the jar files deployed with this application
                at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:55)
                at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:293)
                at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:80)
                at org.apache.jasper.compiler.TagLibraryInfoImpl.generateTldResourcePath(TagLibraryInfoImpl.java:251)
                at org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:122)
                at org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:431)
                at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:489)
                at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1445)
                at org.apache.jasper.compiler.Parser.parse(Parser.java:144)
                at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:244)
                at org.apache.jasper.compiler.ParserController.parse(ParserController.java:105)
                at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:203)
                at org.apache.jasper.compiler.Compiler.compile(Compiler.java:375)
                at org.apache.jasper.compiler.Compiler.compile(Compiler.java:351)
                at org.apache.jasper.compiler.Compiler.compile(Compiler.java:335)
                at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:597)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399)
                at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
                at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:713)
                at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:583)
                at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:519)
                at org.opencms.flex.CmsFlexRequestDispatcher.includeExternal(CmsFlexRequestDispatcher.java:191)
                at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:165)
                at org.opencms.loader.CmsJspLoader.service(CmsJspLoader.java:665)
                at org.opencms.flex.CmsFlexRequestDispatcher.includeInternalWithCache(CmsFlexRequestDispatcher.java:444)

                at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:169)
                at org.opencms.loader.CmsJspLoader.dispatchJsp(CmsJspLoader.java:993)
                at org.opencms.loader.CmsJspLoader.load(CmsJspLoader.java:544)
                at org.opencms.loader.CmsXmlContainerPageLoader.load(CmsXmlContainerPageLoader.java:108)
                at org.opencms.loader.CmsResourceManager.loadResource(CmsResourceManager.java:1194)
                at org.opencms.main.OpenCmsCore.showResource(OpenCmsCore.java:2218)
                at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:325)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.opencms.jsp.jsonpart.CmsJsonPartFilter.doFilter(CmsJsonPartFilter.java:298)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:713)
                at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:462)
                at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:387)
                at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:315)
                at org.opencms.main.OpenCmsUrlServletFilter.doFilter(OpenCmsUrlServletFilter.java:145)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)
```

**Comment by gWestenberger** [comment] 2021-10-18 10:00
Can't reproduce this. Is this a new OpenCms installation, or updated from something else?

**Comment by gWestenberger** [comment] 2022-03-24 09:07
Not reproducible and probably a problem with only very specific version of Tomcat. Closing.

**Closed by gWestenberger** 2022-03-24 09:07 UTC
