### ISSUE TITLE
After upgraded to OpenCMS10, when access "Search Management" error occurs.

### ISSUE THREAD

**Issue by PipC** [alkacon/opencms-core#380] opened 2016-04-10 14:59 UTC
An error occurred.<br />Error while filling the list "Search Indices".

org.opencms.main.CmsRuntimeException: Error while filling the list "Search Indices".
	at org.opencms.workplace.list.A_CmsListDialog.fillList(A_CmsListDialog.java:954)
	at org.opencms.workplace.list.A_CmsListDialog.refreshList(A_CmsListDialog.java:692)
	at org.opencms.workplace.list.A_CmsListDialog.actionDialog(A_CmsListDialog.java:378)
	at org.opencms.workplace.list.A_CmsListDialog.displayDialog(A_CmsListDialog.java:425)
	at org.opencms.workplace.list.A_CmsListDialog.displayDialog(A_CmsListDialog.java:410)
	at org.apache.jsp.WEB_002dINF.jsp.offline.system.workplace.admin.searchindex.index_jsp._jspService(index_jsp.java:67)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:412)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)
	at org.opencms.flex.CmsFlexRequestDispatcher.forward(CmsFlexRequestDispatcher.java:111)
	at org.opencms.loader.CmsJspLoader.load(CmsJspLoader.java:528)
	at org.opencms.loader.CmsResourceManager.loadResource(CmsResourceManager.java:1191)
	at org.opencms.main.OpenCmsCore.showResource(OpenCmsCore.java:1776)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:159)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:412)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)
	at org.opencms.flex.CmsFlexRequestDispatcher.forward(CmsFlexRequestDispatcher.java:111)
	at org.opencms.util.CmsRequestUtil.forwardRequest(CmsRequestUtil.java:492)
	at org.opencms.workplace.tools.CmsToolManager.jspForwardPage(CmsToolManager.java:483)
	at org.opencms.workplace.administration.CmsAdminDialog.displayDialog(CmsAdminDialog.java:92)
	at org.apache.jsp.WEB_002dINF.jsp.offline.system.workplace.views.admin.admin_002dmain_jsp._jspService(admin_002dmain_jsp.java:66)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:412)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)
	at org.opencms.loader.CmsJspLoader.load(CmsJspLoader.java:528)
	at org.opencms.loader.CmsResourceManager.loadResource(CmsResourceManager.java:1191)
	at org.opencms.main.OpenCmsCore.showResource(OpenCmsCore.java:1776)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:159)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.opencms.workplace.tools.searchindex.CmsSearchIndexList.getListItems(CmsSearchIndexList.java:322)
	at org.opencms.workplace.list.A_CmsListDialog.fillList(A_CmsListDialog.java:947)
	... 69 more

**Comment by aKandzior** [comment] 2016-04-18 12:51
With this little information we have no chance to reproduce the issue. 

Please provide in information about your OpenCms search configuration, both before and after the update.

I will have to close the issue as invalid in case we don't get more details from you within the next 3 months.

**Comment by tHerrmann** [comment] 2016-06-16 08:26
Can not be reproduced. 
In case the issue is still present in the latest release version 10.0.1 please re-open with a detailed description how to reproduce the issue.

**Closed by tHerrmann** 2016-06-16 08:26 UTC
Labels: Release 10.0.0

**Comment by bzebedin** [comment] 2016-10-23 12:51
I had the same problem. After upgrading to 10.0.1 I had an additional index
      <index>
        <name>German online help</name>
        <rebuild>auto</rebuild>
        <project>Online</project>
        <locale>de</locale>
        <sources>
          <source>source2</source>
        </sources>
      </index>
in my opencms-search.xml.
After deleting this unused (and in my opinion not correctly configured index) everything worked fine.
