### ISSUE TITLE
Incorrect content-conversion: cleanup;xhtml when special multibyte UTF8 Chars at the end of line

### ISSUE THREAD

**Issue by clemensf** [alkacon/opencms-core#271] opened 2014-07-10 14:33 UTC
**Version:** OpenCms 9.0.1
**Application Server:** Tomcat 7.0.47
**Java JDK:** jdk1.7.0_51

When content-conversion is set to _"cleanup;xhtml"_ for some Cms XML resource the following content is getting converted incorrectly:

```
<content><![CDATA[<p>より高いセキュリティ機能が必要とされる場合には、インフィニオンは非接触ならびにデュアル・インターフェースのハイ・セキュリティ暗号化コントローラの幅広いポートフォリオを提供しています。
<br />
<br />- より高いセキュリティ機能が必要とされる場合には、インフィニオンは非接触ならびにデュアル・インターフェースのハイ・セキュリティ暗号化コントローラの幅広いポートフォリオを提供しています。</p>]]></content>
```

**Result:**

```
<content><![CDATA[<p>より高いセキュリティ機能が必要とされる場合には、インフィニオンは非接触ならびにデュアル・インターフェースのハイ・セキュリティ暗号化コントローラの幅広いポートフォリオを提供しています。
<br />
<br />- より高いセキュリティ機能が必要とされる場合には、インフィニオンは非接触ならびにデュアル・インターフェースのハイ・セキュリティ暗号化コントローラの幅広いポートフォリオを提供しています。&
amp; amp; amp; amp; amp; amp; amp; amp; lt; /p&gt;</p>]]></content>
```
1. Note the chinese fullstop "。" at the end of the line, followed by a closing `</p>` tag.
2. The lines / strings in question have 100 or more characters and are always getting line wrapped at col 100
3. In this case the following `</p>` tag is then getting incorrectly entity-encoded. The entity is then split by the line wrap and somehow the "amp;" fragment is added 10 times.
4. Other occurrences of this bug will result in text fragments like ": : : : : : : : : : " or "s s s s s s s s s s", "g g g g g g g g g g" etc. always appearing after long lines/strings followed by multibyte UTF8 characters (chinese punctuation) like:
   、，。—
5. When the resource is edited and saved, 10 more unwanted chars or html entity fragments will be added.

The bug also occurs with japanese UTF8 chars and also with western latin chars (100+) followed by a multibyte UTF8 char:

```
<br />LoremIpsumDolorSitALoremIpsumDolorSitALoremIpsumDolorSitALoremIpsumDolorSitALoremIpsumDol。</p>
```

The content is getting incorrectly converted, after autocorrection is activated in method 
    org.opencms.xml.content.CmsDefaultXmlContentHandler.prepareForWrite(CmsObject, CmsXmlContent, CmsFile)

and in line 1104 the method
    org.opencms.xml.A_CmsXmlDocument.correctXmlStructure(CmsObject)
is called .

So the bug must be somewhere in method **correctXmlStructure** in class **A_CmsXmlDocument**.

**Comment by aKandzior** [comment] 2016-04-18 12:39
Please check if this is still an issue with either OpenCms 9.5.1 or 10.0.0. If I do not hear back from you within 3 months I will assume the issue is no longer relevant and close it.

**Comment by danham567** [comment] 2019-06-14 12:27
in method
org.opencms.xml.content.CmsDefaultXmlContentHandler.prepareForWrite(CmsObject, CmsXmlContent, CmsFile)[120.pdf](https://github.com/alkacon/opencms-core/files/3290592/120.pdf)

**Closed** 2021-10-01 15:20 UTC
Labels: Create Wiki article
