### ISSUE TITLE
Error deleting unpublished resource

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#521] opened 2017-07-20 20:40 UTC
Steps to reproduce it (with OpenCms 10.0.1):

1. Upload file 2016-17-dummy.pdf to /sites/group/.downloads/testing/
1. Don't publish, directly delete it
1. Deleting error: ![occe_delete_a](https://user-images.githubusercontent.com/2276952/28437430-7ec8733e-6d92-11e7-9a53-5a23bd40d8f8.png)
See a) for full stracktrace.
1. After closing error dialog, file is still visible
1. Reload page
1. File is not visible any more
1. Warning when uploading same file again: ![occe_delete_b](https://user-images.githubusercontent.com/2276952/28437627-3b0ca588-6d93-11e7-9920-e4bebb3803ec.png)
1. Clicking "Ok" results in another error: ![occe_delete_c](https://user-images.githubusercontent.com/2276952/28437634-418eadfc-6d93-11e7-980f-dc0d6c07bbb3.png)
See b) for full stracktrace.

Seems only to happen with installed OCEE Cluster Package.

---
a) Deletion error
```
org.opencms.lock.CmsLockException: Error deleting the resource "/.downloads/testing/2016-17-dummy.pdf".
	at org.opencms.lock.CmsLockException.createException(CmsLockException.java:70)
	at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:335)
	at org.opencms.db.CmsDbContext.report(CmsDbContext.java:287)
	at org.opencms.db.CmsSecurityManager.deleteResource(CmsSecurityManager.java:1594)
	at org.opencms.file.types.A_CmsResourceType.deleteResource(A_CmsResourceType.java:405)
	at org.opencms.file.CmsObject.deleteResource(CmsObject.java:1066)
	at org.opencms.ui.dialogs.CmsDeleteDialog.submit(CmsDeleteDialog.java:239)
	at org.opencms.ui.dialogs.CmsDeleteDialog$2.buttonClick(CmsDeleteDialog.java:126)
	at sun.reflect.GeneratedMethodAccessor286.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1008)
	at com.vaadin.ui.Button.fireClick(Button.java:377)
	at com.vaadin.ui.Button$1.click(Button.java:54)
	at sun.reflect.GeneratedMethodAccessor287.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:408)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:79)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1409)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:364)
	at org.opencms.main.CmsUIServlet.service(CmsUIServlet.java:280)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.opencms.lock.CmsLockException: Unable remove existing resource "/.downloads/testing/2016-17-dummy.pdf" as a deleted resource.
	at org.opencms.lock.CmsLockManager.removeDeletedResource(CmsLockManager.java:502)
	at org.opencms.db.CmsDriverManager.deleteResource(CmsDriverManager.java:3001)
	at org.opencms.db.CmsSecurityManager.deleteResource(CmsSecurityManager.java:7076)
	at org.opencms.db.CmsSecurityManager.deleteResource(CmsSecurityManager.java:1592)
	... 51 more
 ```

b) Creation error
 ```
Error while creating resources on the VFS of OpenCms.

org.opencms.file.CmsVfsResourceNotFoundException: Error reading file "/sites/group/.downloads/testing/2016-17-dummy.pdf". 
	at org.opencms.file.CmsVfsResourceNotFoundException.createException(CmsVfsResourceNotFoundException.java:71)
	at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:335)
	at org.opencms.db.CmsDbContext.report(CmsDbContext.java:287)
	at org.opencms.db.CmsSecurityManager.readFile(CmsSecurityManager.java:4219)
	at org.opencms.file.CmsObject.readFile(CmsObject.java:2494)
	at org.opencms.ade.upload.CmsUploadBean.createSingleResource(CmsUploadBean.java:383)
	at org.opencms.ade.upload.CmsUploadBean.createResources(CmsUploadBean.java:282)
	at org.opencms.ade.upload.CmsUploadBean.start(CmsUploadBean.java:198)
	at org.apache.jsp.WEB_002dINF.jsp.offline.system.workplace.commons.uploadAction_jsp._jspService(uploadAction_jsp.java:112)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:719)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:583)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:522)
	at org.opencms.flex.CmsFlexRequestDispatcher.includeExternal(CmsFlexRequestDispatcher.java:191)
	at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:165)
	at org.opencms.loader.CmsJspLoader.service(CmsJspLoader.java:655)
	at org.opencms.flex.CmsFlexRequestDispatcher.includeInternalWithCache(CmsFlexRequestDispatcher.java:441)
	at org.opencms.flex.CmsFlexRequestDispatcher.include(CmsFlexRequestDispatcher.java:169)
	at org.opencms.loader.CmsJspLoader.dispatchJsp(CmsJspLoader.java:977)
	at org.opencms.loader.CmsJspLoader.load(CmsJspLoader.java:528)
	at org.opencms.loader.CmsResourceManager.loadResource(CmsResourceManager.java:1191)
	at org.opencms.main.OpenCmsCore.showResource(OpenCmsCore.java:1777)
	at org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:161)
	at org.opencms.main.OpenCmsServlet.doPost(OpenCmsServlet.java:177)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.opencms.file.CmsVfsResourceNotFoundException: Unable to read file contents with resource ID "8ecfa722-6d89-11e7-aa63-005056a123b3" (online=false).
	at org.opencms.db.generic.CmsVfsDriver.readContent(CmsVfsDriver.java:1848)
	at org.opencms.ocee.cache.CmsVfsCache.readContent(CmsVfsCache.java:525)
	at org.opencms.db.CmsDriverManager.readFile(CmsDriverManager.java:6812)
	at org.opencms.db.CmsSecurityManager.readFile(CmsSecurityManager.java:4208)
	... 54 more
 ```

**Comment by dSeidel** [comment] 2021-10-06 10:22
I cannot reproduce the issue in the current master branch (being OpenCms 12 soon), so I'll close the issue.

**Closed by dSeidel** 2021-10-06 10:22 UTC
